### ISSUE TITLE
Handle json return type

### ISSUE THREAD

**Issue by FredrikL** [FredrikL/frankie#5]
serialize to json if correct accept headers

**Comment by parnham** [comment]
Just the other week I was thinking that, with the availability of C++11 features, it would now be possible to write a framework similar to Nancy and lo and behold here it is. 

I had envisioned it without templating or HTML, but instead as a REST API dealing with messages in the requests and responses using JSON. The reason that this seemed a logical way to go was because of a C++11 library I have been working on recently called [libentity](https://github.com/emergent-design/libentity). 

There's no reason why frankie couldn't handle both scenarios though, so you may want to consider supporting DTOs in one way or another (boost serialisation perhaps?).

I look forward to seeing how this framework evolves.

**Comment by FredrikL** [comment]
My "plan" right now is to support json/xml input/output first and solve viewengines "later" :)
